const TASK_CREATION = 'TASK_CREATION';
const TASK_UPDATE = 'TASK_UPDATE';
const CATEGORY_CREATION = 'CATEGORY_CREATION';
const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
const MATRIX_CREATION = 'MATRIX_CREATION';
const MATRIX_UPDATE = 'MATRIX_UPDATE';

export {
    TASK_CREATION, TASK_UPDATE,
    CATEGORY_CREATION, CATEGORY_UPDATE,
    MATRIX_CREATION, MATRIX_UPDATE
}